import type { Metadata } from 'next';
import localFont from 'next/font/local';
// import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const adnocSans = localFont({
  src: [
    {
      path: '../public/fonts/ADNOCSans_A_Lt.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/ADNOCSans_A_Md.ttf',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: '--font-adnoc-sans',
});

const helveticaNeueLTArabic = localFont({
  src: [
    {
      path: '../public/fonts/HelveticaNeueLTArabic-Light_2.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/HelveticaNeueLTArabic-Bold_2.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-helvetica-neue-lt-arabic',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`$ ${adnocSans.variable} ${helveticaNeueLTArabic.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
